"""Turn the probe suite's results into the committed Markdown report.

The report is the deliverable, not the console output. SPEC-PLAT-031: a row in
the compatibility table is only as good as the report beside it, and a report
nobody can regenerate is a claim rather than evidence.

    python3 probes/report.py <results.jsonl> <out.md>
"""

import json
import platform
import subprocess
import sys

# SPEC-TEST-041. The class decides what a failure MEANS, not whether it is
# recorded — every probe is recorded either way (SPEC-TEST-042).
CLASS = {
	"entry-symbol": "BLOCKING",
	"line-table": "BLOCKING",
	"struct-fields": "BLOCKING",
	"slice-fields": "BLOCKING",
	"string-value": "HIGH",
	"frame-key-spread": "HIGH",
	"only-student-code": "HIGH",
	"frame-key": "HIGH",
	"finish-breakpoint": "HIGH",
	"simple-return": "HIGH",
	"thread-count": "HIGH",
	"thread-event": "HIGH",
	"thread-count-is-unsound": "HIGH",
	"map-entries": "HIGH",
	"confined-stepping": "HIGH",
	"free-symbol": "MEDIUM",
	"no-debug-info": "MEDIUM",
	"step-cost": "MEDIUM",
}

# Probes whose failure is a KNOWN, documented fact rather than news. Marking
# them keeps the report honest: an expected failure that reads as a surprise
# teaches the next reader the wrong thing.
EXPECTED_FAILURE = {
	"only-student-code": "Expected. 35% of stops landed outside the student's "
	"source on 2026-08-05. The mitigation is SPEC-ADP-014.",
	"map-entries": "Expected. R-20: the map type gives no entry access. Until "
	"that decision is made, a map shows its count and marks its entries unknown.",
}


def run(*command):
	try:
		return subprocess.run(
			command, capture_output=True, text=True, check=False
		).stdout.strip().splitlines()[0]
	except (OSError, IndexError):
		return "unknown"


def main():
	source, destination = sys.argv[1], sys.argv[2]

	entries = [json.loads(line) for line in open(source, encoding="utf-8")]

	# Later groups do not overwrite earlier ones; step-cost is recorded per
	# target, so it is collected separately.
	probes = {}
	step_costs = []
	for entry in entries:
		for name, result in entry["results"].items():
			if name == "step-cost":
				step_costs.append((entry["target"], result))
				continue
			probes.setdefault(name, (entry["target"], result))

	odin = run("odin", "version").replace("odin version ", "")
	gdb = run("gdb", "--version")

	out = []
	add = out.append

	add("# Probe report — %s" % run("date", "+%F"))
	add("")
	add("Generated by `probes/run.sh`. SPEC-TEST-041.")
	add("")
	add("This file is evidence for a row in the compatibility table")
	add("([PLATFORM-SUPPORT.md](../../docs/PLATFORM-SUPPORT.md) §5). A row is added only")
	add("when the suite has run and this report is committed (SPEC-PLAT-031).")
	add("")
	add("## Combination")
	add("")
	add("| | |")
	add("|---|---|")
	add("| Odin | `%s` |" % odin)
	add("| Debugger | %s |" % gdb)
	add("| Platform | %s %s |" % (platform.system(), platform.machine()))
	add("| Build flags | `odin build <file> -file -debug` |")
	add("")

	add("## Results")
	add("")
	add("| Probe | Class | Result | Evidence |")
	add("|---|---|---|---|")
	for name in CLASS:
		if name not in probes:
			continue
		_, result = probes[name]
		if result["ok"]:
			verdict = "**pass**"
		elif name in EXPECTED_FAILURE:
			verdict = "**fail, expected**"
		else:
			verdict = "**FAIL**"
		detail = result["detail"].replace("|", "\\|").replace("\n", " ")
		add("| `%s` | %s | %s | %s |" % (name, CLASS[name], verdict, detail))

	unclassified = sorted(set(probes) - set(CLASS))
	for name in unclassified:
		_, result = probes[name]
		detail = result["detail"].replace("|", "\\|").replace("\n", " ")
		add(
			"| `%s` | — | %s | %s |"
			% (name, "**pass**" if result["ok"] else "**FAIL**", detail)
		)
	add("")

	if step_costs:
		add("## `step-cost`, at three sizes")
		add("")
		add("Recorded with the SPEC-ADP-014 confinement in place, so this is the cost")
		add("of a step the student actually sees, not of a raw `step`.")
		add("")
		add("| Target | Student steps | ms per step |")
		add("|---|---|---|")
		for target, result in step_costs:
			add(
				"| `%s` | %s | %s |"
				% (target, result.get("steps", "—"), result.get("ms_per_step", "—"))
			)
		add("")

	expected = [n for n in probes if n in EXPECTED_FAILURE and not probes[n][1]["ok"]]
	if expected:
		add("## Failures that are not news")
		add("")
		for name in expected:
			add("**`%s`** — %s" % (name, EXPECTED_FAILURE[name]))
			add("")

	surprises = [
		n
		for n, (_, r) in probes.items()
		if not r["ok"] and n not in EXPECTED_FAILURE
	]
	add("## What a reader should take from this run")
	add("")
	blocking_failed = [n for n in surprises if CLASS.get(n) == "BLOCKING"]
	if blocking_failed:
		add("**A BLOCKING probe failed: %s.**" % ", ".join(blocking_failed))
		add("")
		add("ROADMAP Phase 0 says stop rather than work around it. The debug")
		add("information does not support the model on this combination.")
	elif surprises:
		add("Every BLOCKING probe passed. These were not expected to fail and did:")
		add("")
		for name in surprises:
			add("- `%s` (%s)" % (name, CLASS.get(name, "—")))
	else:
		add("Every BLOCKING probe passed, and nothing failed that was not already")
		add("known to fail.")
	add("")
	add("A probe failure is a supported-platform failure, not a bug")
	add("(SPEC-TEST-042). It means this combination is not supported. It does not")
	add("mean the tool is broken.")
	add("")

	with open(destination, "w", encoding="utf-8") as handle:
		handle.write("\n".join(out) + "\n")


main()
